ExtConstructionProjectx.customer_class = 'Kustomerx::Customer'
ExtConstructionProjectx.show_customer_path = 'kustomerx.customer_path(:id => r.customer_id)'
ExtConstructionProjectx.index_contract_path = 'simple_contractx.contracts_path(:project_id => r.project_id)'
ExtConstructionProjectx.contract_resource = 'simple_contractx/contracts'
ExtConstructionProjectx.index_team_member_path = ''
ExtConstructionProjectx.team_member_resource = ''
ExtConstructionProjectx.index_payment_request_path = 'payment_requestx.payment_requests_path(:project_id => r.project_id)'
ExtConstructionProjectx.payment_request_resource = 'payment_requestx/payment_requests'
